version: '3.0'
services:
    mymongodb:
        container_name: mymongodb
        build:
            context: .
            dockerfile: Dockerfile-mongodb
        image: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongovol:/data/db
        restart: always

    myapp:
        container_name: myapp
        build:
            context: .
            dockerfile: Dockerfile
        image: springapp
        ports:
            - "8080:8080"
        links:
            - mymongodb:mymongodb


volumes:
    mongovol: